/// Flutter icons MyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const _kFontPkg = null;

  static const IconData note = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dots = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_read = IconData(0xf316, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_messenger = IconData(0xf39f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
